### ISSUE TITLE
Is this still required?

### ISSUE THREAD

**Issue by finkarder** [TomasHubelbauer/mime-multipart#2]
FYI:
Following link suggests cloudflare now has compatibility flag called "formdata_parser_supports_files".
https://walshy.dev/blog/21_09_10-handling-file-uploads-with-cloudflare-workers

**Comment by TomasHubelbauer** [comment]
Thanks for letting me know! I did note this in the sister repo to this one: https://github.com/TomasHubelbauer/workers-formdata But I forgot to link the repos or mention this here.  Added a banner to the readme.
